### PR TITLE
ci: Add files that tell GitHub to run checks on the package

### PR DESCRIPTION
**Pull request by lwjohnst86**
This PR adds a file in the `.github/workflows/` folder that tells GitHub to run an "Action" on the contents of the repository. In this case the action is to run checks on the package and test that things work in an independent and clean environment. Right now, the action uses a very basic R check that would not be suitable for a CRAN submission, but is a good starting point.

By the way, I created this using `usethis::use_github_action("check-release")`. :grin:

### CODE REVIEW

**Comment by lwjohnst86** [comment]
@signekb and @Aastedet please look this over and approve and then merge in :relaxed:

**Review by signekb — APPROVED** [review]
Nice! I can't say that I fully understand the action script, but as you say, it's probably a good starting point :)

**Review by Aastedet — APPROVED** [review]
Awesome. Lines 5+6 in README.rmd are no longer a merge conflict, hooray!

**Comment by signekb** [comment]
@Aastedet The R-CMD check [fails](https://github.com/steno-aarhus/osdc/actions/runs/7185570920/job/19569138138?pr=17#step:5:74) with the following error message: 
```
L71: * checking whether package ‘osdc’ can be installed ... ERROR
L72: Error: Installation failed.
[...]
L92: Error: Error in here("R/packages.R") : could not find function "here"
L93: Error: Error: unable to load R code in package ‘osdc’
```
It seems that the following scripts call `source(here::here("R/packages.R))` and R/packages.R doesn't exist: 
- `draw_dm_sample.R`
- `filter.R`
- `population.R`

**Comment by lwjohnst86** [comment]
@signekb there will be lots of errors for a while, as we fix issues one by one.

**Pull request merged**
